# Generated by Django 5.1.6 on 2025-03-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mystory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_collaborated',
            field=models.BooleanField(default=False),
        ),
    ]
