# Generated by Django 5.2 on 2025-06-16 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Mystory", "0002_update"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Update",
        ),
    ]
