# Generated by Django 5.1.6 on 2025-03-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mystory', '0002_story_is_collaborated'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='emotions',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='story',
            name='length',
            field=models.CharField(choices=[('short', 'Short'), ('medium', 'Medium'), ('long', 'Long')], default='medium', max_length=10),
        ),
    ]
