# Generated by Django 5.1.6 on 2025-03-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mystory', '0002_alter_story_created_at_alter_story_updated_at'),
        ('Mystory', '0005_collaborationinvite_story_alter_story_created_at_and_more'),
    ]

    operations = [
    ]
