# Generated by Django 5.1.6 on 2025-03-11 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mystory', '0006_merge_20250311_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 3, 11, 17, 7, 32, 182270, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2025, 3, 11, 17, 7, 41, 164770, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
