# Generated by Django 5.1.6 on 2025-03-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mystory', '0007_alter_story_created_at_alter_story_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='story_images/'),
        ),
    ]
