# Generated by Django 5.1.6 on 2025-03-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mystory', '0009_storylike_storyview'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='genre',
            field=models.CharField(blank=True, choices=[('mystery', 'Mystery'), ('romance', 'Romance'), ('fantasy', 'Fantasy'), ('horror', 'Horror')], max_length=50, null=True),
        ),
    ]
