# Generated by Django 5.1.6 on 2025-03-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mystory', '0010_story_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
