# Generated by Django 5.2 on 2025-06-03 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_alter_chatroom_options_alter_message_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatroom",
            options={},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={},
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="message",
            name="is_read",
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="participants",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name="UserStatus",
        ),
    ]
